name: proyectoGrado

on:
  push:
    branches:
      - main
      - master
      - ronald
      - may-jul-2021
      - s-superscript-removal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Clean for Maven
        run: mvn clean
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify --settings ./.mvn/custom-settings.xml
      - name: Code Coverage on Codecov
        uses: codecov/codecov-action@v2
        with:
          token: CODECOV_TOKEN='83b03a9f-0d6e-4bad-adbe-4b767210a934'
      - name: Publish Project on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: HEROKU_API_TOKEN_DEVELOPMENT='3b6e4f97-d99e-496a-84eb-c4d8f800af72'
          heroku_app_name: "testcalclogicronald"
          heroku_email: "ronaldbecerrag@gmail.com"
      - name: Deploy App on Heroku
        run: mvn heroku:deploy-war
